### ISSUE TITLE
Problem with device tree

### ISSUE THREAD

**Issue by LourencoPRT** [antshiv/BLEDroneCode#1]
![image](https://github.com/antshiv/BLEDroneCode/assets/172413277/ea5ccd7f-906c-4fc5-862b-26002817c853)
![image](https://github.com/antshiv/BLEDroneCode/assets/172413277/03c93c78-a89e-4247-a93a-a58cb0c17394)

how did you get this to work? did you make the st,vl53l8.yaml if so coud you include it in the files and if not what's wrong here.
Thanks in advance

**Comment by antshiv** [comment]
You can remove the compatible line if it is causing the problem. Ideally it
should just ignore if it cannot find the file. See if removing the
'compatible' line fixes your issue?

**Comment by LourencoPRT** [comment]
i learned later that the issue was not there, im trying to use the sensor with a nrf52dk but i only want to use the vl53l8 and  through I2C, and not use all the other sensors. altough if i remove the compatible line i get this
![image](https://github.com/antshiv/BLEDroneCode/assets/172413277/c0d368e5-e9ff-4c4c-be4f-f44a1add9632)

**Comment by antshiv** [comment]
Ah! Hope it all works now.

**Comment by antshiv** [comment]
I had problems using this with i2c. If you do get it working consistently
with i2c, feel free to make a PR.
